highlighter: rouge
safe: true
lsi: false
permalink: "/:title/"

kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-coffeescript
    - jekyll-paginate

lsi: false

future: false

excerpt_separator: <!--more-->

defaults:
    -
        scope:
            path: ""    # empty string for all files
            type: posts # limit to posts
        values:
            amp: true   # enabled amp for posts
